// <auto-generated />
namespace AribilgiWebProject.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Version15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version15));
        
        string IMigrationMetadata.Id
        {
            get { return "202211190919478_Version-1.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
